name: pandas-ai-2026
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas=2.1.*
  - numpy=1.24.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - jupyter=1.0.*
  - jupyter-lab=4.*
  - ipykernel=6.25.*
  - scikit-learn=1.3.*
  - plotly=5.17.*
  - openpyxl=3.1.*
  - xlrd=2.0.*
  - pip=23.*
  - pip:
    - ydata-profiling==4.6.*
    - python-dotenv==1.0.*
    - requests==2.31.*
    - beautifulsoup4==4.12.*
    - lxml==4.9.*